version: "3"
services:
  validation-server:
    build: ./validation-server
    ports: 
      - "4000:4000"
    volumes:
      - ./validation-server:/app
      - /app/node_modules
  app_1:
    build: ./app
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
    - ID=111
    tty: true
  
  app_2: 
    build: ./app
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
    - ID=222
    tty: true
