version: "3"
services:
  validation-server:
    build: ./validation-server
    restart: always
    ports: 
      - "4000:4000"
    volumes:
      - ./validation-server:/app
  app_1:
    build: ./app
    restart: always
    volumes:
      - ./app:/app
    environment:
    - PC=111
    tty: true
  
  app_2: 
    build: ./app
    restart: always
    volumes:
      - ./app:/app
    environment:
    - PC=222
    tty: true
